/**
 * Represents a specific part of a message that involves tool execution UI.
 * Used to track the state and results of tools called by the AI.
 */
export interface ToolUIPart {
  type: 'tool-ui';
  toolCallId: string; // Unique ID for finding/updating this specific call
  toolName: string; // Name of the tool (e.g., 'webSearch')
  args: unknown; // Original arguments sent by the LLM
  result?: unknown; // Final output returned by the tool
  state: // Lifecycle of the tool call
    | 'input-streaming'
    | 'input-available'
    | 'approval-requested'
    | 'approval-responded'
    | 'output-available'
    | 'output-error'
    | 'output-denied';
  input?: unknown;
  output?: unknown;
  errorText?: string;
}

/**
 * Represents a downloadable/viewable file generated by the AI.
 */
export interface FileUIPart {
  type: 'file';
  url: string; // External link (S3/R2)
  mediaType?: string; // Mime type (image/png, application/pdf)
  filename?: string; // Original name
  data?: string; // Base64 or raw data if applicable
}

export type ChatStatus = 'streaming' | 'submitted' | 'ready' | 'error';

export interface LanguageModelUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  inputTokens?: number;
  outputTokens?: number;
  reasoningTokens?: number;
  cachedInputTokens?: number;
}

export interface Experimental_GeneratedImage {
  base64?: string;
  mediaType?: string;
  url?: string;
}

export interface TextPart {
  type: 'text';
  text: string;
}

export interface ReasoningPart {
  type: 'reasoning';
  reasoning: string;
}

export type MessagePart = TextPart | ToolUIPart | ReasoningPart;

/**
 * The standard message structure used throughout the application.
 */
export interface Message {
  id: string; // Unique message ID
  role: 'user' | 'assistant' | 'system' | 'data' | 'tool'; // Sender role
  content: string | MessagePart[]; // Can be plain text or structured parts
}
