/**
 * Aura-2 Speaker Registry
 * Maps technical model names to human personas for the AI to use in script writing.
 * Contains all available Aura-2 speakers across multiple languages.
 */
export interface SpeakerCharacter {
  name: string;
  model: string; // The full model string, e.g., 'aura-2-thalia-en'
  gender: 'male' | 'female';
  language: string;
  languageCode: string;
  accent: string;
  description: string;
  provider: 'deepgram' | 'google';
}

/**
 * Complete list of available AI speaker characters.
 * Organized by language and vocal personality.
 */
export const auraSpeakers: SpeakerCharacter[] = [
  // --- ENGLISH (en) ---
  {
    name: 'Thalia',
    model: 'aura-2-thalia-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Clear, Confident, Energetic, Enthusiastic. Great for casual chat, customer service, and IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Andromeda',
    model: 'aura-2-andromeda-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Casual, Expressive, Comfortable. Best for customer service and IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Helena',
    model: 'aura-2-helena-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Caring, Natural, Positive, Friendly, Raspy. Ideal for IVR and casual chat.',
    provider: 'deepgram',
  },
  {
    name: 'Apollo',
    model: 'aura-2-apollo-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Confident, Comfortable, Casual. Perfect for casual chat.',
    provider: 'deepgram',
  },
  {
    name: 'Arcas',
    model: 'aura-2-arcas-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Natural, Smooth, Clear, Comfortable. Great for customer service and casual chat.',
    provider: 'deepgram',
  },
  {
    name: 'Aries',
    model: 'aura-2-aries-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Warm, Energetic, Caring. Best for casual chat.',
    provider: 'deepgram',
  },
  {
    name: 'Amalthea',
    model: 'aura-2-amalthea-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'Filipino',
    description: 'Engaging, Natural, Cheerful. Casual chat specialist.',
    provider: 'deepgram',
  },
  {
    name: 'Asteria',
    model: 'aura-2-asteria-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Clear, Confident, Knowledgeable, Energetic. Recommended for advertising.',
    provider: 'deepgram',
  },
  {
    name: 'Athena',
    model: 'aura-2-athena-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Calm, Smooth, Professional. Perfect for storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Atlas',
    model: 'aura-2-atlas-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Enthusiastic, Confident, Approachable, Friendly. Great for advertising.',
    provider: 'deepgram',
  },
  {
    name: 'Aurora',
    model: 'aura-2-aurora-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Cheerful, Expressive, Energetic. Ideal for interviews.',
    provider: 'deepgram',
  },
  {
    name: 'Callista',
    model: 'aura-2-callista-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Clear, Energetic, Professional, Smooth. Optimized for IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Cora',
    model: 'aura-2-cora-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Smooth, Melodic, Caring. Perfect for storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Cordelia',
    model: 'aura-2-cordelia-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Approachable, Warm, Polite. Great for storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Delia',
    model: 'aura-2-delia-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Casual, Friendly, Cheerful, Breathy. Best for interviews.',
    provider: 'deepgram',
  },
  {
    name: 'Draco',
    model: 'aura-2-draco-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'British',
    description: 'Warm, Approachable, Trustworthy, Baritone. Ideal for storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Electra',
    model: 'aura-2-electra-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Professional, Engaging, Knowledgeable. Great for IVR, advertising, and customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Harmonia',
    model: 'aura-2-harmonia-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Empathetic, Clear, Calm, Confident. Specialist in customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Hera',
    model: 'aura-2-hera-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Smooth, Warm, Professional. Best for informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Hermes',
    model: 'aura-2-hermes-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Expressive, Engaging, Professional. Great for informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Hyperion',
    model: 'aura-2-hyperion-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'Australian',
    description: 'Caring, Warm, Empathetic. Ideal for interviews.',
    provider: 'deepgram',
  },
  {
    name: 'Iris',
    model: 'aura-2-iris-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Cheerful, Positive, Approachable. Great for IVR, advertising, and customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Janus',
    model: 'aura-2-janus-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Southern, Smooth, Trustworthy. Perfect for storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Juno',
    model: 'aura-2-juno-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Natural, Engaging, Melodic, Breathy. Great for interviews.',
    provider: 'deepgram',
  },
  {
    name: 'Jupiter',
    model: 'aura-2-jupiter-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Expressive, Knowledgeable, Baritone. Best for informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Luna',
    model: 'aura-2-luna-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Friendly, Natural, Engaging. Optimized for IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Mars',
    model: 'aura-2-mars-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Smooth, Patient, Trustworthy, Baritone. Great for customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Minerva',
    model: 'aura-2-minerva-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Positive, Friendly, Natural. Ideal for storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Neptune',
    model: 'aura-2-neptune-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Professional, Patient, Polite. Great for customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Odysseus',
    model: 'aura-2-odysseus-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Calm, Smooth, Comfortable, Professional. Recommended for advertising.',
    provider: 'deepgram',
  },
  {
    name: 'Ophelia',
    model: 'aura-2-ophelia-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Expressive, Enthusiastic, Cheerful. Ideal for interviews.',
    provider: 'deepgram',
  },
  {
    name: 'Orion',
    model: 'aura-2-orion-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Approachable, Comfortable, Calm, Polite. Best for informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Orpheus',
    model: 'aura-2-orpheus-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Professional, Clear, Confident, Trustworthy. Ideal for customer service and storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Pandora',
    model: 'aura-2-pandora-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'British',
    description: 'Smooth, Calm, Melodic, Breathy. Great for IVR and informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Phoebe',
    model: 'aura-2-phoebe-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Energetic, Warm, Casual. Great for customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Pluto',
    model: 'aura-2-pluto-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Smooth, Calm, Empathetic, Baritone. Ideal for interviews and storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Saturn',
    model: 'aura-2-saturn-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Knowledgeable, Confident, Baritone. Great for customer service.',
    provider: 'deepgram',
  },
  {
    name: 'Selene',
    model: 'aura-2-selene-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Expressive, Engaging, Energetic. Best for informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Theia',
    model: 'aura-2-theia-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'Australian',
    description: 'Expressive, Polite, Sincere. Ideal for informative content.',
    provider: 'deepgram',
  },
  {
    name: 'Vesta',
    model: 'aura-2-vesta-en',
    gender: 'female',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Natural, Expressive, Patient, Empathetic. Great for customer service, interview, and storytelling.',
    provider: 'deepgram',
  },
  {
    name: 'Zeus',
    model: 'aura-2-zeus-en',
    gender: 'male',
    language: 'English',
    languageCode: 'en',
    accent: 'American',
    description: 'Deep, Trustworthy, Smooth. Optimized for IVR.',
    provider: 'deepgram',
  },

  // --- SPANISH (es) ---
  {
    name: 'Celeste',
    model: 'aura-2-celeste-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Colombian',
    description: 'Clear, Energetic, Positive, Friendly, Enthusiastic. Great for Casual Chat, Advertising, and IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Estrella',
    model: 'aura-2-estrella-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Mexican',
    description: 'Approachable, Natural, Calm, Comfortable, Expressive. Ideal for Casual Chat and Interview.',
    provider: 'deepgram',
  },
  {
    name: 'Nestor',
    model: 'aura-2-nestor-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Peninsular',
    description: 'Calm, Professional, Approachable, Clear, Confident. Great for Casual Chat and Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Sirio',
    model: 'aura-2-sirio-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Mexican',
    description: 'Calm, Professional, Comfortable, Empathetic, Baritone. Best for Casual Chat and Interview.',
    provider: 'deepgram',
  },
  {
    name: 'Carina',
    model: 'aura-2-carina-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Peninsular',
    description: 'Professional, Raspy, Energetic, Breathy, Confident. Ideal for Interview, Customer Service, and IVR. Supports codeswitching with English.',
    provider: 'deepgram',
  },
  {
    name: 'Alvaro',
    model: 'aura-2-alvaro-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Peninsular',
    description: 'Calm, Professional, Clear, Knowledgeable, Approachable. Great for Interview and Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Diana',
    model: 'aura-2-diana-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Peninsular',
    description: 'Professional, Confident, Expressive, Polite, Knowledgeable. Best for Storytelling and Advertising. Supports codeswitching with English.',
    provider: 'deepgram',
  },
  {
    name: 'Aquila',
    model: 'aura-2-aquila-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Latin American',
    description: 'Expressive, Enthusiastic, Confident, Casual, Comfortable. Ideal for Casual Chat and Informative content. Supports codeswitching with English.',
    provider: 'deepgram',
  },
  {
    name: 'Selena',
    model: 'aura-2-selena-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Latin American',
    description: 'Approachable, Casual, Friendly, Calm, Positive. Great for Customer Service and Informative content. Supports codeswitching with English.',
    provider: 'deepgram',
  },
  {
    name: 'Javier',
    model: 'aura-2-javier-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Mexican',
    description: 'Approachable, Professional, Friendly, Comfortable, Calm. Great for Casual Chat, IVR, and Storytelling. Supports codeswitching with English.',
    provider: 'deepgram',
  },
  {
    name: 'Agustina',
    model: 'aura-2-agustina-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Peninsular',
    description: 'Calm, Clear, Expressive, Knowledgeable, Professional. Best for Interview and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Antonia',
    model: 'aura-2-antonia-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Argentine',
    description: 'Approachable, Enthusiastic, Friendly, Natural, Professional. Ideal for Customer Service, Interview, and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Gloria',
    model: 'aura-2-gloria-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Colombian',
    description: 'Casual, Clear, Expressive, Natural, Smooth. Great for Customer Service and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Luciano',
    model: 'aura-2-luciano-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Mexican',
    description: 'Charismatic, Cheerful, Energetic, Expressive, Friendly. Ideal for Customer Service and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Olivia',
    model: 'aura-2-olivia-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Mexican',
    description: 'Breathy, Calm, Casual, Expressive, Warm. Great for Customer Service and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Silvia',
    model: 'aura-2-silvia-es',
    gender: 'female',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Peninsular',
    description: 'Charismatic, Clear, Expressive, Natural, Warm. Best for Customer Service and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Valerio',
    model: 'aura-2-valerio-es',
    gender: 'male',
    language: 'Spanish',
    languageCode: 'es',
    accent: 'Mexican',
    description: 'Deep, Knowledgeable, Natural, Polite, Professional. Ideal for Customer Service and Informative content.',
    provider: 'deepgram',
  },

  // --- DUTCH (nl) ---
  {
    name: 'Rhea',
    model: 'aura-2-rhea-nl',
    gender: 'female',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Caring, Knowledgeable, Positive, Smooth, Warm. Great for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Sander',
    model: 'aura-2-sander-nl',
    gender: 'male',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Calm, Clear, Deep, Professional, Smooth. Ideal for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Beatrix',
    model: 'aura-2-beatrix-nl',
    gender: 'female',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Cheerful, Enthusiastic, Friendly, Trustworthy, Warm. Best for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Daphne',
    model: 'aura-2-daphne-nl',
    gender: 'female',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Calm, Clear, Confident, Professional, Smooth. Ideal for Healthcare, Interview, Casual Chat, and Audiobooks.',
    provider: 'deepgram',
  },
  {
    name: 'Cornelia',
    model: 'aura-2-cornelia-nl',
    gender: 'female',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Approachable, Friendly, Polite, Positive, Warm. Great for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Hestia',
    model: 'aura-2-hestia-nl',
    gender: 'female',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Approachable, Caring, Expressive, Friendly, Knowledgeable. Ideal for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Lars',
    model: 'aura-2-lars-nl',
    gender: 'male',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Breathy, Casual, Comfortable, Sincere, Trustworthy. Best for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Roman',
    model: 'aura-2-roman-nl',
    gender: 'male',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Calm, Casual, Deep, Natural, Patient. Ideal for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Leda',
    model: 'aura-2-leda-nl',
    gender: 'female',
    language: 'Dutch',
    languageCode: 'nl',
    accent: 'Dutch',
    description: 'Caring, Comfortable, Empathetic, Friendly, Sincere. Recommended for Sales.',
    provider: 'deepgram',
  },

  // --- FRENCH (fr) ---
  {
    name: 'Agathe',
    model: 'aura-2-agathe-fr',
    gender: 'female',
    language: 'French',
    languageCode: 'fr',
    accent: 'French',
    description: 'Charismatic, Cheerful, Enthusiastic, Friendly, Natural. Great for Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Hector',
    model: 'aura-2-hector-fr',
    gender: 'male',
    language: 'French',
    languageCode: 'fr',
    accent: 'French',
    description: 'Confident, Empathetic, Expressive, Friendly, Patient. Ideal for Customer Service.',
    provider: 'deepgram',
  },

  // --- GERMAN (de) ---
  {
    name: 'Julius',
    model: 'aura-2-julius-de',
    gender: 'male',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Casual, Cheerful, Engaging, Expressive, Friendly. Great for Customer Service and Healthcare.',
    provider: 'deepgram',
  },
  {
    name: 'Viktoria',
    model: 'aura-2-viktoria-de',
    gender: 'female',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Charismatic, Cheerful, Enthusiastic, Friendly, Warm. Ideal for Customer Service and Sales.',
    provider: 'deepgram',
  },
  {
    name: 'Elara',
    model: 'aura-2-elara-de',
    gender: 'female',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Calm, Clear, Natural, Patient, Trustworthy. Recommended for Healthcare and Financial Services.',
    provider: 'deepgram',
  },
  {
    name: 'Aurelia',
    model: 'aura-2-aurelia-de',
    gender: 'female',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Approachable, Casual, Comfortable, Natural, Sincere. Great for Customer Service and Sales.',
    provider: 'deepgram',
  },
  {
    name: 'Lara',
    model: 'aura-2-lara-de',
    gender: 'female',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Caring, Cheerful, Empathetic, Expressive, Warm. Ideal for Healthcare and Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Fabian',
    model: 'aura-2-fabian-de',
    gender: 'male',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Confident, Knowledgeable, Natural, Polite, Professional. Great for Financial Services.',
    provider: 'deepgram',
  },
  {
    name: 'Kara',
    model: 'aura-2-kara-de',
    gender: 'female',
    language: 'German',
    languageCode: 'de',
    accent: 'German',
    description: 'Caring, Empathetic, Expressive, Professional, Warm. Ideal for Healthcare.',
    provider: 'deepgram',
  },

  // --- ITALIAN (it) ---
  {
    name: 'Livia',
    model: 'aura-2-livia-it',
    gender: 'female',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Approachable, Cheerful, Clear, Engaging, Expressive. Great for Customer Service and Audiobooks.',
    provider: 'deepgram',
  },
  {
    name: 'Dionisio',
    model: 'aura-2-dionisio-it',
    gender: 'male',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Confident, Engaging, Friendly, Melodic, Positive. Ideal for Sales and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Melia',
    model: 'aura-2-melia-it',
    gender: 'female',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Clear, Comfortable, Engaging, Friendly, Natural. Best for Casual Chat and Interview.',
    provider: 'deepgram',
  },
  {
    name: 'Elio',
    model: 'aura-2-elio-it',
    gender: 'male',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Breathy, Calm, Professional, Smooth, Trustworthy. Ideal for Interview and Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Flavio',
    model: 'aura-2-flavio-it',
    gender: 'male',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Confident, Deep, Empathetic, Professional, Trustworthy. Great for Casual Chat and Interview.',
    provider: 'deepgram',
  },
  {
    name: 'Maia',
    model: 'aura-2-maia-it',
    gender: 'female',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Caring, Energetic, Expressive, Professional, Warm. Best for Interview and Healthcare.',
    provider: 'deepgram',
  },
  {
    name: 'Cinzia',
    model: 'aura-2-cinzia-it',
    gender: 'female',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Approachable, Friendly, Smooth, Trustworthy, Warm. Great for Narration and Interview.',
    provider: 'deepgram',
  },
  {
    name: 'Cesare',
    model: 'aura-2-cesare-it',
    gender: 'male',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Clear, Empathetic, Knowledgeable, Natural, Smooth. Ideal for IVR and Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Perseo',
    model: 'aura-2-perseo-it',
    gender: 'male',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Casual, Clear, Natural, Polite, Smooth. Best for Casual Chat and Customer Service.',
    provider: 'deepgram',
  },
  {
    name: 'Demetra',
    model: 'aura-2-demetra-it',
    gender: 'female',
    language: 'Italian',
    languageCode: 'it',
    accent: 'Italian',
    description: 'Calm, Comfortable, Patient. Great for Narration and Casual Chat.',
    provider: 'deepgram',
  },

  // --- JAPANESE (ja) ---
  {
    name: 'Fujin',
    model: 'aura-2-fujin-ja',
    gender: 'male',
    language: 'Japanese',
    languageCode: 'ja',
    accent: 'Japanese',
    description: 'Calm, Confident, Knowledgeable, Professional, Smooth. Ideal for Interview and IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Izanami',
    model: 'aura-2-izanami-ja',
    gender: 'female',
    language: 'Japanese',
    languageCode: 'ja',
    accent: 'Japanese',
    description: 'Approachable, Clear, Knowledgeable, Polite, Professional. Best for Customer Service and IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Uzume',
    model: 'aura-2-uzume-ja',
    gender: 'female',
    language: 'Japanese',
    languageCode: 'ja',
    accent: 'Japanese',
    description: 'Approachable, Clear, Polite, Professional, Trustworthy. Ideal for Commercial and IVR.',
    provider: 'deepgram',
  },
  {
    name: 'Ebisu',
    model: 'aura-2-ebisu-ja',
    gender: 'male',
    language: 'Japanese',
    languageCode: 'ja',
    accent: 'Japanese',
    description: 'Calm, Deep, Natural, Patient, Sincere. Great for Casual Chat.',
    provider: 'deepgram',
  },
  {
    name: 'Ama',
    model: 'aura-2-ama-ja',
    gender: 'female',
    language: 'Japanese',
    languageCode: 'ja',
    accent: 'Japanese',
    description: 'Casual, Comfortable, Confident, Knowledgeable, Natural. Best for Interview and IVR.',
    provider: 'deepgram',
  },
];

/**
 * Gemini-specific voices for multi-speaker podcast generation.
 */
export const geminiVoices: SpeakerCharacter[] = [
  { name: 'Zephyr', model: 'Zephyr', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Bright and energetic.', provider: 'google' },
  { name: 'Puck', model: 'Puck', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Upbeat and lively.', provider: 'google' },
  { name: 'Charon', model: 'Charon', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Informative and steady.', provider: 'google' },
  { name: 'Kore', model: 'Kore', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Firm and authoritative.', provider: 'google' },
  { name: 'Fenrir', model: 'Fenrir', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Excitable and high-energy.', provider: 'google' },
  { name: 'Leda', model: 'Leda', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Youthful and fresh.', provider: 'google' },
  { name: 'Orus', model: 'Orus', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Firm and confident.', provider: 'google' },
  { name: 'Aoede', model: 'Aoede', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Breezy and light.', provider: 'google' },
  { name: 'Callirrhoe', model: 'Callirrhoe', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Easy-going and relaxed.', provider: 'google' },
  { name: 'Autonoe', model: 'Autonoe', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Bright and clear.', provider: 'google' },
  { name: 'Enceladus', model: 'Enceladus', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Breathy and intimate.', provider: 'google' },
  { name: 'Iapetus', model: 'Iapetus', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Clear and articulate.', provider: 'google' },
  { name: 'Umbriel', model: 'Umbriel', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Easy-going and calm.', provider: 'google' },
  { name: 'Algieba', model: 'Algieba', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Smooth and melodic.', provider: 'google' },
  { name: 'Despina', model: 'Despina', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Smooth and consistent.', provider: 'google' },
  { name: 'Erinome', model: 'Erinome', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Clear and precise.', provider: 'google' },
  { name: 'Algenib', model: 'Algenib', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Gravelly and textured.', provider: 'google' },
  { name: 'Rasalgethi', model: 'Rasalgethi', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Informative and professional.', provider: 'google' },
  { name: 'Laomedeia', model: 'Laomedeia', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Upbeat and positive.', provider: 'google' },
  { name: 'Achernar', model: 'Achernar', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Soft and gentle.', provider: 'google' },
  { name: 'Alnilam', model: 'Alnilam', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Firm and steady.', provider: 'google' },
  { name: 'Schedar', model: 'Schedar', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Even and balanced.', provider: 'google' },
  { name: 'Gacrux', model: 'Gacrux', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Mature and resonant.', provider: 'google' },
  { name: 'Pulcherrima', model: 'Pulcherrima', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Forward and engaging.', provider: 'google' },
  { name: 'Achird', model: 'Achird', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Friendly and approachable.', provider: 'google' },
  { name: 'Zubenelgenubi', model: 'Zubenelgenubi', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Casual and relaxed.', provider: 'google' },
  { name: 'Vindemiatrix', model: 'Vindemiatrix', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Gentle and kind.', provider: 'google' },
  { name: 'Sadachbia', model: 'Sadachbia', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Lively and spirited.', provider: 'google' },
  { name: 'Sadaltager', model: 'Sadaltager', gender: 'male', language: 'English', languageCode: 'en', accent: 'American', description: 'Knowledgeable and wise.', provider: 'google' },
  { name: 'Sulafat', model: 'Sulafat', gender: 'female', language: 'English', languageCode: 'en', accent: 'American', description: 'Warm and comforting.', provider: 'google' },
];
